
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jul 10 09:38:49 COT 2012
//----------------------------------------------------

package Compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 42;
  public static final int ENTERO = 36;
  public static final int DIFERENTE = 24;
  public static final int STDIO = 13;
  public static final int H = 7;
  public static final int MENORIGUAL = 26;
  public static final int IGUAL = 4;
  public static final int MENOSNUM = 18;
  public static final int CAB = 10;
  public static final int SINO = 31;
  public static final int LETRA = 41;
  public static final int PARENTI = 5;
  public static final int IOSTREAM = 12;
  public static final int MAIN = 14;
  public static final int KAMA = 29;
  public static final int PARENTD = 6;
  public static final int MASNUM = 20;
  public static final int COMIS = 17;
  public static final int MAYORIGUAL = 25;
  public static final int PYCOMA = 23;
  public static final int EOF = 0;
  public static final int HINAQA = 3;
  public static final int error = 1;
  public static final int COMA = 22;
  public static final int CADENA = 37;
  public static final int MENOS = 33;
  public static final int MENOR = 28;
  public static final int VOID = 15;
  public static final int REAL = 38;
  public static final int MAYOR = 27;
  public static final int PAQ = 9;
  public static final int PUNTO = 8;
  public static final int QILLQAY = 16;
  public static final int INCLUIR = 11;
  public static final int MENOSUNO = 19;
  public static final int HACER = 30;
  public static final int MULTI = 34;
  public static final int LLAVEI = 39;
  public static final int MASUNO = 21;
  public static final int LLAVED = 40;
  public static final int ENTRE = 35;
  public static final int ARI = 2;
  public static final int MAS = 32;
}

